
export const mockPerformanceData = {
  metrics: [
    {
      id: 'total-deliveries',
      label: 'Total Pengiriman',
      value: '12,450',
      unit: 'paket',
      change: 15,
      icon: 'Package',
      color: 'primary' as const,
    },
    {
      id: 'success-rate',
      label: 'Tingkat Keberhasilan',
      value: '98.5',
      unit: '%',
      change: 2.3,
      icon: 'CheckCircle2',
      color: 'success' as const,
    },
    {
      id: 'avg-delivery-time',
      label: 'Rata-rata Waktu Pengiriman',
      value: '2.4',
      unit: 'hari',
      change: -5,
      icon: 'Clock',
      color: 'warning' as const,
    },
    {
      id: 'total-revenue',
      label: 'Total Pendapatan',
      value: 'Rp 2.5M',
      unit: '',
      change: 22,
      icon: 'DollarSign',
      color: 'primary' as const,
    },
  ],

  deliveryPerformance: [
    { name: 'Minggu 1', 'Berhasil': 95, 'Gagal': 5 },
    { name: 'Minggu 2', 'Berhasil': 97, 'Gagal': 3 },
    { name: 'Minggu 3', 'Berhasil': 96, 'Gagal': 4 },
    { name: 'Minggu 4', 'Berhasil': 98, 'Gagal': 2 },
    { name: 'Minggu 5', 'Berhasil': 99, 'Gagal': 1 },
  ],

  deliveryStatus: [
    { name: 'Terkirim', value: 85 },
    { name: 'Dalam Perjalanan', value: 10 },
    { name: 'Menunggu', value: 3 },
    { name: 'Gagal', value: 2 },
  ],

  monthlyRevenue: [
    { name: 'Jan', 'Pendapatan': 180000000 },
    { name: 'Feb', 'Pendapatan': 195000000 },
    { name: 'Mar', 'Pendapatan': 210000000 },
    { name: 'Apr', 'Pendapatan': 205000000 },
    { name: 'May', 'Pendapatan': 225000000 },
    { name: 'Jun', 'Pendapatan': 240000000 },
    { name: 'Jul', 'Pendapatan': 255000000 },
    { name: 'Aug', 'Pendapatan': 270000000 },
    { name: 'Sep', 'Pendapatan': 260000000 },
    { name: 'Oct', 'Pendapatan': 280000000 },
    { name: 'Nov', 'Pendapatan': 295000000 },
    { name: 'Dec', 'Pendapatan': 310000000 },
  ],

  deliveryVolume: [
    { name: 'Jan', 'Volume': 850 },
    { name: 'Feb', 'Volume': 920 },
    { name: 'Mar', 'Volume': 1050 },
    { name: 'Apr', 'Volume': 980 },
    { name: 'May', 'Volume': 1120 },
    { name: 'Jun', 'Volume': 1200 },
    { name: 'Jul', 'Volume': 1280 },
    { name: 'Aug', 'Volume': 1350 },
    { name: 'Sep', 'Volume': 1300 },
    { name: 'Oct', 'Volume': 1400 },
    { name: 'Nov', 'Volume': 1480 },
    { name: 'Dec', 'Volume': 1550 },
  ],

  yearlyTrend: [
    { name: 'Jan', 'Performa': 92, 'Target': 95 },
    { name: 'Feb', 'Performa': 94, 'Target': 95 },
    { name: 'Mar', 'Performa': 95, 'Target': 95 },
    { name: 'Apr', 'Performa': 93, 'Target': 95 },
    { name: 'May', 'Performa': 96, 'Target': 95 },
    { name: 'Jun', 'Performa': 97, 'Target': 95 },
    { name: 'Jul', 'Performa': 98, 'Target': 95 },
    { name: 'Aug', 'Performa': 99, 'Target': 95 },
    { name: 'Sep', 'Performa': 97, 'Target': 95 },
    { name: 'Oct', 'Performa': 98, 'Target': 95 },
    { name: 'Nov', 'Performa': 99, 'Target': 95 },
    { name: 'Dec', 'Performa': 98.5, 'Target': 95 },
  ],

  customerSatisfaction: [
    { name: 'Jan', 'Rating': 4.2 },
    { name: 'Feb', 'Rating': 4.3 },
    { name: 'Mar', 'Rating': 4.4 },
    { name: 'Apr', 'Rating': 4.3 },
    { name: 'May', 'Rating': 4.5 },
    { name: 'Jun', 'Rating': 4.6 },
    { name: 'Jul', 'Rating': 4.7 },
    { name: 'Aug', 'Rating': 4.8 },
    { name: 'Sep', 'Rating': 4.7 },
    { name: 'Oct', 'Rating': 4.8 },
    { name: 'Nov', 'Rating': 4.9 },
    { name: 'Dec', 'Rating': 4.85 },
  ],

  detailTable: [
    {
      id: '1',
      date: '2024-12-15',
      service: 'Express Same Day',
      deliveries: 450,
      successful: 445,
      failed: 5,
      successRate: 98.9,
      avgTime: '4 jam',
      revenue: 'Rp 22.5M',
    },
    {
      id: '2',
      date: '2024-12-15',
      service: 'Regular 1-2 Days',
      deliveries: 1200,
      successful: 1176,
      failed: 24,
      successRate: 98.0,
      avgTime: '1.8 hari',
      revenue: 'Rp 36M',
    },
    {
      id: '3',
      date: '2024-12-15',
      service: 'Drone Delivery',
      deliveries: 280,
      successful: 278,
      failed: 2,
      successRate: 99.3,
      avgTime: '2 jam',
      revenue: 'Rp 28M',
    },
    {
      id: '4',
      date: '2024-12-14',
      service: 'Express Same Day',
      deliveries: 420,
      successful: 410,
      failed: 10,
      successRate: 97.6,
      avgTime: '4.2 jam',
      revenue: 'Rp 21M',
    },
    {
      id: '5',
      date: '2024-12-14',
      service: 'Regular 1-2 Days',
      deliveries: 1150,
      successful: 1127,
      failed: 23,
      successRate: 98.0,
      avgTime: '1.9 hari',
      revenue: 'Rp 34.5M',
    },
    {
      id: '6',
      date: '2024-12-14',
      service: 'Drone Delivery',
      deliveries: 260,
      successful: 257,
      failed: 3,
      successRate: 98.8,
      avgTime: '2.1 jam',
      revenue: 'Rp 26M',
    },
    {
      id: '7',
      date: '2024-12-13',
      service: 'Express Same Day',
      deliveries: 480,
      successful: 475,
      failed: 5,
      successRate: 98.96,
      avgTime: '3.9 jam',
      revenue: 'Rp 24M',
    },
    {
      id: '8',
      date: '2024-12-13',
      service: 'Regular 1-2 Days',
      deliveries: 1280,
      successful: 1254,
      failed: 26,
      successRate: 97.97,
      avgTime: '1.7 hari',
      revenue: 'Rp 38.4M',
    },
  ],
}
